import top from "./components/top";
import stories from "./components/story";
import discounts from "./components/discount";
import supermarket from "./components/supermarket";
import scroll from "./components/scroll";
import pink from "./components/pink";
import fourpics from "./components/fourpic";
import surprise from "./components/surprise";
import category from "./components/category";
import undercat from "./components/undercat";
import brand from "./components/brand";
import underbrand from "./components/underbrand";
import mobile from "./components/mobile";
import kifcover from "./components/kifcover";
import headhand from "./components/headhand";
import lapelectra from "./components/lapelectra";
import hots from "./components/hots";
import fourpic2 from "./components/fourpic2";
import best from "./components/best";
import woon from "./components/woon";
import smartwatch from "./components/smartwatch";
import menwatch from "./components/menwatch";
import lavazem from "./components/lavazem";
import menshort from "./components/menshort";
import hothour from "./components/hothour";
import reading from "./components/reading";
import brandend from "./components/brandend";

top();
stories();
discounts();
supermarket();
scroll();
pink();
fourpics();
surprise();
category();
undercat();
brand();
underbrand();
mobile();
kifcover();
headhand();
lapelectra();
hots();
fourpic2();
best();
woon();
smartwatch();
menwatch();
lavazem();
menshort();
hothour();
reading();
brandend();
